default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.3.0
    hooks:
    -   id: check-executables-have-shebangs
        stages: [push]
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
        stages: [push]
    -   id: check-toml
        stages: [push]
    -   id: check-yaml
        stages: [push]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: Running black from local poetry env
        entry: poetry run black .
        # Black does not work with language as python
        language: system
        types:
          - python
    -   id: flake8
        name: Running flake8 from local poetry env
        entry: poetry run flake8 .
        language: python
        files: ".*.py"
    -   id: isort
        name: Running isort from local poetry env
        entry: poetry run isort .
        language: python
        files: ".*.py"
